const provincia = [
    { id: "01", id_departamento: "1", name: "Chachapoyas" },
    { id: "02", id_departamento: "1", name: "Bagua" },
    { id: "03", id_departamento: "1", name: "Bongara" },
    { id: "04", id_departamento: "1", name: "Condorcanqui" },
    { id: "05", id_departamento: "1", name: "Luya" },
    { id: "06", id_departamento: "1", name: "Rodriguez de Mendoza" },
    { id: "07", id_departamento: "1", name: "Utcubamba" },
    { id: "01", id_departamento: "2", name: "Huaraz" },
    { id: "02", id_departamento: "2", name: "Aija" },
    { id: "03", id_departamento: "2", name: "Antonio Raymondi" },
    { id: "04", id_departamento: "2", name: "Asuncion" },
    { id: "05", id_departamento: "2", name: "Bolognesi" },
    { id: "06", id_departamento: "2", name: "Carhuaz" },
    { id: "07", id_departamento: "2", name: "Carlos Fermin Fitzcarrald" },
    { id: "08", id_departamento: "2", name: "Casma" },
    { id: "09", id_departamento: "2", name: "Corongo" },
    { id: "10", id_departamento: "2", name: "Huari" },
    { id: "11", id_departamento: "2", name: "Huarmey" },
    { id: "12", id_departamento: "2", name: "Huaylas" },
    { id: "13", id_departamento: "2", name: "Mariscal Luzuriaga" },
    { id: "14", id_departamento: "2", name: "Ocros" },
    { id: "15", id_departamento: "2", name: "Pallasca" },
    { id: "16", id_departamento: "2", name: "Pomabamba" },
    { id: "17", id_departamento: "2", name: "Recuay" },
    { id: "18", id_departamento: "2", name: "Santa" },
    { id: "19", id_departamento: "2", name: "Sihuas" },
    { id: "20", id_departamento: "2", name: "Yungay" },
    { id: "01", id_departamento: "3", name: "Abancay" },
    { id: "02", id_departamento: "3", name: "Andahuaylas" },
    { id: "03", id_departamento: "3", name: "Antabamba" },
    { id: "04", id_departamento: "3", name: "Aymaraes" },
    { id: "05", id_departamento: "3", name: "Cotabambas" },
    { id: "06", id_departamento: "3", name: "Chincheros" },
    { id: "07", id_departamento: "3", name: "Grau" },
    { id: "01", id_departamento: "4", name: "Arequipa" },
    { id: "02", id_departamento: "4", name: "Camana" },
    { id: "03", id_departamento: "4", name: "Caraveli" },
    { id: "04", id_departamento: "4", name: "Castilla" },
    { id: "05", id_departamento: "4", name: "Caylloma" },
    { id: "06", id_departamento: "4", name: "Condesuyos" },
    { id: "07", id_departamento: "4", name: "Islay" },
    { id: "08", id_departamento: "4", name: "La Union" },
    { id: "01", id_departamento: "5", name: "Huamanga" },
    { id: "02", id_departamento: "5", name: "Cangallo" },
    { id: "03", id_departamento: "5", name: "Huanca Sancos" },
    { id: "04", id_departamento: "5", name: "Huanta" },
    { id: "05", id_departamento: "5", name: "La Mar" },
    { id: "06", id_departamento: "5", name: "Lucanas" },
    { id: "07", id_departamento: "5", name: "Parinacochas" },
    { id: "08", id_departamento: "5", name: "Paucar del Sara Sara" },
    { id: "09", id_departamento: "5", name: "Sucre" },
    { id: "10", id_departamento: "5", name: "Victor Fajardo" },
    { id: "11", id_departamento: "5", name: "Vilcas Huaman" },
    { id: "01", id_departamento: "6", name: "Cajamarca" },
    { id: "02", id_departamento: "6", name: "Cajabamba" },
    { id: "03", id_departamento: "6", name: "Celendin" },
    { id: "04", id_departamento: "6", name: "Chota" },
    { id: "05", id_departamento: "6", name: "Contumaza" },
    { id: "06", id_departamento: "6", name: "Cutervo" },
    { id: "07", id_departamento: "6", name: "Hualgayoc" },
    { id: "08", id_departamento: "6", name: "Jaen" },
    { id: "09", id_departamento: "6", name: "San Ignacio" },
    { id: "10", id_departamento: "6", name: "San Marcos" },
    { id: "11", id_departamento: "6", name: "San Miguel" },
    { id: "12", id_departamento: "6", name: "San Pablo" },
    { id: "13", id_departamento: "6", name: "Santa Cruz" },
    { id: "01", id_departamento: "7", name: "Prov. Const. del Callao" },
    { id: "01", id_departamento: "8", name: "Cusco" },
    { id: "02", id_departamento: "8", name: "Acomayo" },
    { id: "03", id_departamento: "8", name: "Anta" },
    { id: "04", id_departamento: "8", name: "Calca" },
    { id: "05", id_departamento: "8", name: "Canas" },
    { id: "06", id_departamento: "8", name: "Canchis" },
    { id: "07", id_departamento: "8", name: "Chumbivilcas" },
    { id: "08", id_departamento: "8", name: "Espinar" },
    { id: "09", id_departamento: "8", name: "La Convencion" },
    { id: "10", id_departamento: "8", name: "Paruro" },
    { id: "11", id_departamento: "8", name: "Paucartambo" },
    { id: "12", id_departamento: "8", name: "Quispicanchi" },
    { id: "13", id_departamento: "8", name: "Urubamba" },
    { id: "01", id_departamento: "9", name: "Huancavelica" },
    { id: "02", id_departamento: "9", name: "Acobamba" },
    { id: "03", id_departamento: "9", name: "Angaraes" },
    { id: "04", id_departamento: "9", name: "Castrovirreyna" },
    { id: "05", id_departamento: "9", name: "Churcampa" },
    { id: "06", id_departamento: "9", name: "Huaytara" },
    { id: "07", id_departamento: "9", name: "Tayacaja" },
    { id: "01", id_departamento: "10", name: "Huanuco" },
    { id: "02", id_departamento: "10", name: "Ambo" },
    { id: "03", id_departamento: "10", name: "Dos de Mayo" },
    { id: "04", id_departamento: "10", name: "Huacaybamba" },
    { id: "05", id_departamento: "10", name: "Huamalies" },
    { id: "06", id_departamento: "10", name: "Leoncio Prado" },
    { id: "07", id_departamento: "10", name: "Marañon" },
    { id: "08", id_departamento: "10", name: "Pachitea" },
    { id: "09", id_departamento: "10", name: "Puerto Inca" },
    { id: "10", id_departamento: "10", name: "Lauricocha" },
    { id: "11", id_departamento: "10", name: "Yarowilca" },
    { id: "01", id_departamento: "11", name: "Ica" },
    { id: "02", id_departamento: "11", name: "Chincha" },
    { id: "03", id_departamento: "11", name: "Nasca" },
    { id: "04", id_departamento: "11", name: "Palpa" },
    { id: "05", id_departamento: "11", name: "Pisco" },
    { id: "01", id_departamento: "12", name: "Huancayo" },
    { id: "02", id_departamento: "12", name: "Concepcion" },
    { id: "03", id_departamento: "12", name: "Chanchamayo" },
    { id: "04", id_departamento: "12", name: "Jauja" },
    { id: "05", id_departamento: "12", name: "Junin" },
    { id: "06", id_departamento: "12", name: "Satipo" },
    { id: "07", id_departamento: "12", name: "Tarma" },
    { id: "08", id_departamento: "12", name: "Yauli" },
    { id: "09", id_departamento: "12", name: "Chupaca" },
    { id: "01", id_departamento: "13", name: "Trujillo" },
    { id: "02", id_departamento: "13", name: "Ascope" },
    { id: "03", id_departamento: "13", name: "Bolivar" },
    { id: "04", id_departamento: "13", name: "Chepen" },
    { id: "05", id_departamento: "13", name: "Julcan" },
    { id: "06", id_departamento: "13", name: "Otuzco" },
    { id: "07", id_departamento: "13", name: "Pacasmayo" },
    { id: "08", id_departamento: "13", name: "Pataz" },
    { id: "09", id_departamento: "13", name: "Sanchez Carrion" },
    { id: "10", id_departamento: "13", name: "Santiago de Chuco" },
    { id: "11", id_departamento: "13", name: "Gran Chimu" },
    { id: "12", id_departamento: "13", name: "Viru" },
    { id: "01", id_departamento: "14", name: "Chiclayo" },
    { id: "02", id_departamento: "14", name: "Ferreñafe" },
    { id: "03", id_departamento: "14", name: "Lambayeque" },
    { id: "01", id_departamento: "15", name: "Lima" },
    { id: "02", id_departamento: "15", name: "Barranca" },
    { id: "03", id_departamento: "15", name: "Cajatambo" },
    { id: "04", id_departamento: "15", name: "Canta" },
    { id: "05", id_departamento: "15", name: "Cañete" },
    { id: "06", id_departamento: "15", name: "Huaral" },
    { id: "07", id_departamento: "15", name: "Huarochiri" },
    { id: "08", id_departamento: "15", name: "Huaura" },
    { id: "09", id_departamento: "15", name: "Oyon" },
    { id: "10", id_departamento: "15", name: "Yauyos" },
    { id: "01", id_departamento: "16", name: "Maynas" },
    { id: "02", id_departamento: "16", name: "Alto Amazonas" },
    { id: "03", id_departamento: "16", name: "Loreto" },
    { id: "04", id_departamento: "16", name: "Mariscal Ramon Castilla" },
    { id: "05", id_departamento: "16", name: "Requena" },
    { id: "06", id_departamento: "16", name: "Ucayali" },
    { id: "07", id_departamento: "16", name: "Datem del Marañon" },
    { id: "08", id_departamento: "16", name: "Putumayo" },
    { id: "01", id_departamento: "17", name: "Tambopata" },
    { id: "02", id_departamento: "17", name: "Manu" },
    { id: "03", id_departamento: "17", name: "Tahuamanu" },
    { id: "01", id_departamento: "18", name: "Mariscal Nieto" },
    { id: "02", id_departamento: "18", name: "General Sanchez Cerro" },
    { id: "03", id_departamento: "18", name: "Ilo" },
    { id: "01", id_departamento: "19", name: "Pasco" },
    { id: "02", id_departamento: "19", name: "Daniel Alcides Carrion" },
    { id: "03", id_departamento: "19", name: "Oxapampa" },
    { id: "01", id_departamento: "20", name: "Piura" },
    { id: "02", id_departamento: "20", name: "Ayabaca" },
    { id: "03", id_departamento: "20", name: "Huancabamba" },
    { id: "04", id_departamento: "20", name: "Morropon" },
    { id: "05", id_departamento: "20", name: "Paita" },
    { id: "06", id_departamento: "20", name: "Sullana" },
    { id: "07", id_departamento: "20", name: "Talara" },
    { id: "08", id_departamento: "20", name: "Sechura" },
    { id: "01", id_departamento: "21", name: "Puno" },
    { id: "02", id_departamento: "21", name: "Azangaro" },
    { id: "03", id_departamento: "21", name: "Carabaya" },
    { id: "04", id_departamento: "21", name: "Chucuito" },
    { id: "05", id_departamento: "21", name: "El Collao" },
    { id: "06", id_departamento: "21", name: "Huancane" },
    { id: "07", id_departamento: "21", name: "Lampa" },
    { id: "08", id_departamento: "21", name: "Melgar" },
    { id: "09", id_departamento: "21", name: "Moho" },
    { id: "10", id_departamento: "21", name: "San Antonio de Putina" },
    { id: "11", id_departamento: "21", name: "San Roman" },
    { id: "12", id_departamento: "21", name: "Sandia" },
    { id: "13", id_departamento: "21", name: "Yunguyo" },
    { id: "01", id_departamento: "22", name: "Moyobamba" },
    { id: "02", id_departamento: "22", name: "Bellavista" },
    { id: "03", id_departamento: "22", name: "El Dorado" },
    { id: "04", id_departamento: "22", name: "Huallaga" },
    { id: "05", id_departamento: "22", name: "Lamas" },
    { id: "06", id_departamento: "22", name: "Mariscal Caceres" },
    { id: "07", id_departamento: "22", name: "Picota" },
    { id: "08", id_departamento: "22", name: "Rioja" },
    { id: "09", id_departamento: "22", name: "San Martin" },
    { id: "10", id_departamento: "22", name: "Tocache" },
    { id: "01", id_departamento: "23", name: "Tacna" },
    { id: "02", id_departamento: "23", name: "Candarave" },
    { id: "03", id_departamento: "23", name: "Jorge Basadre" },
    { id: "04", id_departamento: "23", name: "Tarata" },
    { id: "01", id_departamento: "24", name: "Tumbes" },
    { id: "02", id_departamento: "24", name: "Contralmirante Villar" },
    { id: "03", id_departamento: "24", name: "Zarumilla" },
    { id: "01", id_departamento: "25", name: "Coronel Portillo" },
    { id: "02", id_departamento: "25", name: "Atalaya" },
    { id: "03", id_departamento: "25", name: "Padre Abad" },
    { id: "04", id_departamento: "25", name: "Puru" }
]
export default provincia;